#!/usr/bin/env python3
import argparse, json, re, time
from urllib.parse import urlparse

def safe_name(s):
    s = re.sub(r"[^A-Za-z0-9_]+", "", s or "")
    return s or "AutoProvider"

ap = argparse.ArgumentParser()
ap.add_argument("--scan", required=True)
ap.add_argument("--url", required=True)
ap.add_argument("--kind", default="movie")
ap.add_argument("--provider-name", default="")
ap.add_argument("--output", required=True)
a = ap.parse_args()

with open(a.scan, encoding="utf-8") as f:
    scan = json.load(f)

host = urlparse(a.url).netloc.split(":")[0]
name = safe_name(a.provider_name) if a.provider_name else safe_name(host.split(".")[0].title()) + "Provider"

manifest = {
    "schema": "cloudstream-builder-manifest/v1",
    "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    "site": {
        "url": a.url,
        "host": host,
        "kind": a.kind
    },
    "provider": {
        "name": name,
        "package": "com.darknesslord.autogenerated",
        "class_name": name
    },
    "discovery": {
        "paths": scan.get("discovered_paths", []),
        "categories": scan.get("category_candidates", []),
        "api_candidates": scan.get("api_candidates", []),
        "media_candidates": scan.get("media_candidates", [])
    },
    "build": {
        "requires_gradle_project": True,
        "task": "make",
        "output_extension": ".cs3"
    }
}

with open(a.output, "w", encoding="utf-8") as f:
    json.dump(manifest, f, ensure_ascii=False, indent=2)
print(name)
